name: 2. Build and Push Docker Image

on:
  workflow_run:
    workflows: ["1. Auto Format with Black"]
    types:
      - completed
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    # Only run if the previous workflow succeeded or was skipped (no changes needed)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # This ensures we get the latest code with any formatting changes
          ref: ${{ github.ref }}

      # Set up Docker Buildx (optional but recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers to speed up subsequent builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chatbot:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          # Pass environment variables securely as build arguments
          build-args: |
            GEMINI_API=${{ secrets.GEMINI_API }}
            MONGO_URI=${{ secrets.MONGO_URI }}
            
      # This step is needed to properly handle the cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache